In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [2]:
def split_scalar(X,y):
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train,X_test,y_train, y_test

def perform_lda(indpen_X,dep_Y,n):
    lda = LDA(n_components = n)
    X_train = lda.fit_transform(indpen_X,dep_Y)
    return lda, X_train

In [3]:
def logistic(X_train, y_train,X_test):
    from sklearn.linear_model import LogisticRegression
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return cm,accuracy,classifier

def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier


def knn(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier


def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    cm,accuracy,classifier = cm_predition(classifier,X_test)
    return  cm,accuracy,classifier

def cm_predition (classifier,X_test):
    y_pred = classifier.predict(X_test)
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred)
    from sklearn.metrics import accuracy_score
    accuracy= accuracy_score(y_test, y_pred)
    return cm,accuracy,classifier

In [4]:
def lda_merge(acclog,accsvmlin,accsvmnl,accnav,accknn,accdec,accrand):
    dataframe=pd.DataFrame(index=['LDA n=2'],columns=['Logistic','SVMlin','SVMNL','Navie','KNN','DT','RF'])
    for number,index in enumerate(dataframe.index):
        dataframe['Logistic'][index]=acclog[number]
        dataframe['SVMlin'][index]=accsvmlin[number]
        dataframe['SVMNL'][index]=accsvmnl[number]
        dataframe['Navie'][index]=accnav[number]
        dataframe['KNN'][index]=accknn[number]
        dataframe['DT'][index]=accdec[number]
        dataframe['RF'][index]=accrand[number]
    return dataframe

In [5]:
dataset1 = pd.read_csv("Automobilecodedata.csv",index_col=None)
df2 = dataset1
df2 = pd.get_dummies(df2, drop_first=True)

indep_X = df2.drop(['displacement', 'weight', 'model_year', 'cylinders'], axis=1)
dep_Y = df2['mpg']

In [6]:
df2

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name_amc ambassador dpl,name_amc ambassador sst,name_amc concord,...,name_volvo 245,name_volvo 264gl,name_volvo diesel,name_vw dasher (diesel),name_vw pickup,name_vw rabbit,name_vw rabbit c (diesel),name_vw rabbit custom,origin_japan,origin_usa
0,18.0,8.0,307.0,130.0,3504.0,12.0,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,15.0,8.0,350.0,165.0,3693.0,11.5,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,18.0,8.0,318.0,150.0,3436.0,11.0,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,16.0,8.0,304.0,150.0,3433.0,12.0,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,17.0,8.0,302.0,140.0,3449.0,10.5,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4.0,140.0,86.0,2790.0,15.6,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
394,44.0,4.0,97.0,52.0,2130.0,24.6,82.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
395,32.0,4.0,135.0,84.0,2295.0,11.6,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
396,28.0,4.0,120.0,79.0,2625.0,18.6,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
397,31.0,4.0,119.0,82.0,2720.0,19.4,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.datasets import make_classification

# Define or load your dataset
# Example with synthetic data
indep_X, dep_Y = make_classification(n_samples=100, n_features=5, n_classes=2, random_state=42)

# Function to perform LDA
def perform_lda(X, y, n_components):
    lda = LinearDiscriminantAnalysis(n_components=n_components)
    X_lda = lda.fit_transform(X, y)
    return lda, X_lda

# Apply LDA
lda, X_train_lda = perform_lda(indep_X, dep_Y, 1)

# Created empty lists to append the final accuracy values for different models
acclog = []
accsvmlin = []
accsvmnl = []
accnav = []
accknn = []
accdec = []
accrand = []

# You can now proceed with model training and evaluation, appending accuracy values to the lists

In [8]:
X_train, X_test, y_train, y_test=split_scalar(X_train_lda,dep_Y)

cm,accuracy,classifier=logistic(X_train,y_train,X_test)
acclog.append(accuracy)

cm,accuracy,classifier=svm_linear(X_train,y_train,X_test)
accsvmlin.append(accuracy)

cm,accuracy,classifier=svm_NL(X_train,y_train,X_test)
accsvmnl.append(accuracy)

cm,accuracy,classifier=Navie(X_train,y_train,X_test)
accnav.append(accuracy)

cm,accuracy,classifier=knn(X_train,y_train,X_test)
accknn.append(accuracy)

cm,accuracy,classifier=Decision(X_train,y_train,X_test)
accdec.append(accuracy)

cm,accuracy,classifier=random(X_train,y_train,X_test)
accrand.append(accuracy)
    
result =lda_merge(acclog,accsvmlin,accsvmnl,accnav,accknn,accdec,accrand)

In [9]:
result#1

        Logistic SVMlin SVMNL Navie   KNN    DT   RF
LDA n=2     0.95   0.95  0.95  0.95  0.95  0.95  1.0